# action.yml
name: 'DataHub Ingestion Action'
description: 'Ingest Data to DataHub'
inputs:
  recipe_file:
    description: 'path of recipe file'
    required: true
  cli_version:
    description: 'cli version to use'
    required: false
    default: v0.10.0.6
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.recipe_file }}
    - ${{ inputs.cli_version }}